"""Stub generated by 'pld plugin new'. Implement the missing methods.

TODO: replace THIS docstring with a real explanation of the format
this plugin handles. It's not a stylistic detail: it's what
'pld plugin info {{plugin_slug}}' shows to anyone who installs your
plugin without ever having read your code. Include at least:
- what the input/output file looks like (a concrete example helps)
- any required vs optional columns/fields
- known limits (max size, allowed values, etc.)
"""
from __future__ import annotations

from pathlib import Path

from payload.core.ir import PLUGIN_API_VERSION, TableIR


class {{plugin_class}}:
    name = "{{plugin_slug}}"
    api_version = PLUGIN_API_VERSION

    # --- reader only: remove if you're writing a writer ---
    extensions = [".{{plugin_slug}}"]
    # Optional: suggested writer when the user doesn't specify --to.
    # Remove the line (or leave None) if there's no obvious default.
    default_writer = None

    def sniff(self, path: Path) -> bool:
        return False

    def parse(self, path: Path, config: dict) -> TableIR:
        raise NotImplementedError("TODO: implement parsing")

    # --- writer only: remove if you're writing a reader ---
    extension = ".{{plugin_slug}}"
    # Optional: if your writer only makes sense with specific readers
    # (because it needs particular semantics in ir.extra), list them here.
    # None = compatible with any reader (default behavior).
    compatible_readers = None

    def emit(self, ir: TableIR, out_path: Path, config: dict) -> Path:
        raise NotImplementedError("TODO: implement writing")
