"""
c_source reader and obj writer tests WITH a real toolchain (gcc/objcopy),
not mocked — it's the only way to be sure the generated commands are
really correct, not just plausible.

If gcc/objcopy aren't available in the CI/development environment,
these tests are skipped (not failed) — see the 'toolchain_available' fixture.
"""
import shutil
import subprocess

import pytest

from payload.core.errors import ReaderParseError, ToolchainExecutionError, WriterEmitError
from payload.core.ir import TableIR
from tests.example_plugins_helper import load_example_plugin

CSourceReader = load_example_plugin("c_source.py").CSourceReader
_obj_writer_module = load_example_plugin("obj_writer.py")
ObjWriter = _obj_writer_module.ObjWriter
section_name_for = _obj_writer_module.section_name_for

pytestmark = pytest.mark.skipif(
    shutil.which("gcc") is None or shutil.which("objcopy") is None,
    reason="requires real gcc and objcopy in the environment",
)


def _host_objcopy_target_arch() -> tuple[str, str]:
    """Determines the objcopy target/arch for the current host, so the
    tests run on any machine (not just x86_64) without hardcoding."""
    result = subprocess.run(["objcopy", "--info"], capture_output=True, text=True)
    output = result.stdout + result.stderr
    if "elf64-x86-64" in output:
        return "elf64-x86-64", "i386:x86-64"
    if "elf32-i386" in output:
        return "elf32-i386", "i386"
    if "elf64-littleaarch64" in output:
        return "elf64-littleaarch64", "aarch64"
    pytest.skip("host architecture not recognized for the test, add a case")


@pytest.fixture
def toolchain_config():
    return {"plugin": {"c_source": {"compiler": "gcc", "compiler_flags": [], "objcopy": "objcopy"}}}


@pytest.fixture
def obj_config():
    target, arch = _host_objcopy_target_arch()
    return {"plugin": {"obj": {"objcopy": "objcopy", "objcopy_target": target, "objcopy_arch": arch}}}


C_SOURCE_VALID = '''#include <stdint.h>

const uint8_t table_data[] __attribute__((section("payload_table_data"))) = {
    0x0A, 0x1B,  // min threshold
    0x2C, 0x3D,  // max threshold
};
'''


def test_c_source_reader_compiles_and_extracts_bytes(tmp_path, toolchain_config):
    c_file = tmp_path / "temp_table.c"
    c_file.write_text(C_SOURCE_VALID)

    ir = CSourceReader().parse(c_file, toolchain_config)

    assert ir.data == bytes([0x0A, 0x1B, 0x2C, 0x3D])
    assert ir.source_format == "c_source"


def test_c_source_reader_extracts_comments_best_effort(tmp_path, toolchain_config):
    c_file = tmp_path / "t.c"
    c_file.write_text(C_SOURCE_VALID)

    ir = CSourceReader().parse(c_file, toolchain_config)

    assert ir.comments == [(0, "min threshold"), (2, "max threshold")]


def test_c_source_reader_compile_error_raises_with_stderr(tmp_path, toolchain_config):
    c_file = tmp_path / "bad.c"
    c_file.write_text("this is not valid C !!! {{{")

    with pytest.raises(ToolchainExecutionError) as exc_info:
        CSourceReader().parse(c_file, toolchain_config)
    assert exc_info.value.context["returncode"] != 0


def test_c_source_reader_missing_section_raises_clear_error(tmp_path, toolchain_config):
    c_file = tmp_path / "nosection.c"
    c_file.write_text("const int x = 42;\n")

    with pytest.raises(ReaderParseError):
        CSourceReader().parse(c_file, toolchain_config)


def test_obj_writer_produces_real_linkable_object(tmp_path, obj_config):
    ir = TableIR(name="temp_table", data=bytes([0x0A, 0x1B, 0x2C, 0x3D]), source_path=tmp_path, source_format="fake")
    out_path = tmp_path / "temp_table.o"

    ObjWriter().emit(ir, out_path, obj_config)

    assert out_path.exists()
    # verify with objdump that the section really exists with the right name and contains the right bytes
    result = subprocess.run(
        ["objdump", "-s", "-j", "table_temp_table", str(out_path)], capture_output=True, text=True
    )
    assert result.returncode == 0
    assert "0a1b2c3d" in result.stdout.replace(" ", "")


def test_obj_writer_missing_target_config_raises(tmp_path):
    ir = TableIR(name="t", data=b"\x01\x02", source_path=tmp_path, source_format="fake")
    with pytest.raises(WriterEmitError):
        ObjWriter().emit(ir, tmp_path / "out.o", {"plugin": {"obj": {}}})


def test_obj_writer_output_actually_links_with_start_stop_symbols(tmp_path, obj_config):
    """The most important test: a real C program links the produced
    .o and reads the data through the __start_/__stop_ symbols
    generated by the linker — this is the core promise of the whole
    'obj' writer."""
    ir = TableIR(name="link_test", data=bytes([0xAA, 0xBB, 0xCC]), source_path=tmp_path, source_format="fake")
    obj_path = tmp_path / "link_test.o"
    ObjWriter().emit(ir, obj_path, obj_config)

    section = section_name_for("link_test")
    main_c = tmp_path / "main.c"
    main_c.write_text(f'''
#include <stdio.h>
extern unsigned char __start_{section}[];
extern unsigned char __stop_{section}[];
int main() {{
    size_t size = __stop_{section} - __start_{section};
    printf("%zu", size);
    for (size_t i = 0; i < size; i++) printf(",%02x", __start_{section}[i]);
    return 0;
}}
''')
    exe_path = tmp_path / "test_link"
    compile_result = subprocess.run(
        ["gcc", str(main_c), str(obj_path), "-o", str(exe_path)],
        capture_output=True, text=True,
    )
    assert compile_result.returncode == 0, compile_result.stderr

    run_result = subprocess.run([str(exe_path)], capture_output=True, text=True)
    assert run_result.stdout == "3,aa,bb,cc"


def test_section_name_sanitizes_invalid_chars():
    assert section_name_for("temp_table") == "table_temp_table"
    assert section_name_for("temp-table") == "table_temp_table"
    assert section_name_for("temp.table") == "table_temp_table"


def test_section_name_never_starts_with_digit():
    name = section_name_for("123start")
    assert not name[0].isdigit()
    assert name == "table_123start"
