"""
Produces a linkable .o with the data in a dedicated section, named
after the table name (sanitized into a valid C identifier).

This is what makes the __start_<section>/__stop_<section> symbols
available once the .o is linked into the final firmware: GNU ld
generates them automatically for every "orphan" section whose name is
a valid C identifier — no need for a custom linker script or to
generate those symbols here (documented in the GNU ld manual, "orphan
sections" section).

Requires 'objcopy_target' (your MCU's bfd target, e.g.
'elf32-littlearm' for ARM) and 'objcopy_arch' (e.g. 'arm') under
[plugin.obj] in table-tool.toml — 'objcopy -I binary' has no universal
default, it depends on the target."""
from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path

from payload.core.doctor import ToolchainCheck
from payload.core.errors import ToolchainExecutionError, WriterEmitError
from payload.core.ir import PLUGIN_API_VERSION, TableIR

_INVALID_CHARS_RE = re.compile(r"[^a-zA-Z0-9_]")


def section_name_for(table_name: str) -> str:
    """Sanitizes the table name into a valid C identifier, prefixed
    with 'table_' — needed because GNU ld only generates the
    __start_X/__stop_X symbols if X is a valid C identifier. The
    prefix alone is enough to guarantee it never starts with a digit,
    whatever the original table name is."""
    sanitized = _INVALID_CHARS_RE.sub("_", table_name)
    return f"table_{sanitized}"


class ObjWriter:
    """Writes a .o with TableIR.data in a section named
    'table_<table name>' (sanitized), ready to be linked into the
    firmware with the __start_/__stop_ symbols generated by the final
    linker. See the module docstring for the config requirements."""

    name = "obj"
    extension = ".o"
    api_version = PLUGIN_API_VERSION

    def emit(self, ir: TableIR, out_path: Path, config: dict) -> Path:
        plugin_cfg = config.get("plugin", {}).get("obj", {})
        objcopy = plugin_cfg.get("objcopy", "objcopy")
        target = plugin_cfg.get("objcopy_target") or ""
        arch = plugin_cfg.get("objcopy_arch") or ""

        if not target or not arch:
            raise WriterEmitError(
                self.name,
                "requires 'objcopy_target' and 'objcopy_arch' under [plugin.obj] in "
                'table-tool.toml (e.g. objcopy_target = "elf32-littlearm", objcopy_arch = "arm")',
            )

        section = section_name_for(ir.name)

        # PRIVATE subfolder, same reason as c_source.py: tmp/ is shared
        # across several stages of a pipeline, it shouldn't all be deleted.
        tmp = ir.source_path.parent / "tmp" / "obj_writer_scratch"
        tmp.mkdir(parents=True, exist_ok=True)
        try:
            bin_path = tmp / "input.bin"
            bin_path.write_bytes(ir.data)

            cmd = [
                objcopy, "-I", "binary", "-O", target, "-B", arch,
                "--rename-section", f".data={section},alloc,load,readonly,data,contents",
                str(bin_path), str(out_path),
            ]
            try:
                result = subprocess.run(cmd, capture_output=True, text=True)
            except FileNotFoundError as e:
                raise ToolchainExecutionError(
                    cmd, -1, f"executable not found: '{objcopy}' ({e})"
                ) from e
            if result.returncode != 0:
                raise ToolchainExecutionError(cmd, result.returncode, result.stderr)
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

        return out_path


class _ObjToolchainCheck(ToolchainCheck):
    """DOCTOR_CHECK must be a bare zero-arg-constructible class (same
    convention as READER/WRITER, see core/local_plugins.py) — this
    wraps ToolchainCheck's 3 required constructor args so the loader
    can instantiate it with none. 'name' is overridden so it doesn't
    collide with c_source.py's own ToolchainCheck-based DOCTOR_CHECK
    when both are registered together (PluginRegistry keys doctor
    checks by name)."""

    name = "toolchain_obj"

    def __init__(self):
        super().__init__("objcopy", "objcopy", "obj")


WRITER = ObjWriter
DOCTOR_CHECK = _ObjToolchainCheck
