"""
Local plugins: reader/writer/doctor-check defined in a single .py
file, loaded without going through 'pip install'. Meant for quick
experiments or formats specific to a single project — for a plugin
reusable across multiple projects, a real pip package (pld plugin new)
is still the right choice (versionable, distributable, installable via
an internal index).

Two ways a file gets discovered:
1. A 'local_plugins/' folder next to table-tool.toml (or anywhere
   inside project_root) — scanned automatically.
2. The PAYLOAD_PLUGIN_PATH environment variable — a list of additional
   folders separated by os.pathsep, searched anywhere on the
   filesystem.

Convention inside the .py file: it exposes the plugin classes as
module-level variables, singular or plural:

    class MyReader:
        name = "my_format"
        ...

    READER = MyReader          # singular: one plugin
    # or
    READERS = [MyReader, ...]  # plural: several plugins in the same file

Same for WRITER/WRITERS and DOCTOR_CHECK/DOCTOR_CHECKS.

If the plugin needs third-party libraries not already present in
payload's environment, declare them with a module-level REQUIRES:

    REQUIRES = ["numpy>=1.20", "pyserial"]

Checked BEFORE attempting to load the module (static read of the
source, without executing it) — so even though the module would fail
with an unclear ModuleNotFoundError, the reported error says exactly
which dependency is missing. 'pld plugin install-deps <file>' installs
them with pip into the current environment."""
from __future__ import annotations

import ast
import importlib.util
import logging
import os
import re
from pathlib import Path
from typing import TYPE_CHECKING

from payload.core.errors import MissingPluginDependenciesError, PluginLoadError
from payload.core.plugin_base import check_api_compatibility

if TYPE_CHECKING:
    from payload.core.registry import PluginRegistry

logger = logging.getLogger(__name__)

LOCAL_PLUGINS_DIRNAME = "local_plugins"
ENV_VAR_NAME = "PAYLOAD_PLUGIN_PATH"

_ATTR_MAP = (
    ("READER", "READERS", "reader"),
    ("WRITER", "WRITERS", "writer"),
    ("DOCTOR_CHECK", "DOCTOR_CHECKS", "doctor_check"),
)

_REQ_NAME_RE = re.compile(r"^[A-Za-z0-9_.\-]+")


def read_requires_static(path: Path) -> list[str]:
    """Reads REQUIRES = [...] from the source WITHOUT executing it
    (AST parsing) — works even if the module isn't importable because
    it's missing precisely the dependency REQUIRES would declare."""
    try:
        tree = ast.parse(path.read_text())
    except (SyntaxError, OSError):
        return []
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(t, ast.Name) and t.id == "REQUIRES" for t in node.targets
        ):
            if isinstance(node.value, (ast.List, ast.Tuple)):
                return [
                    elt.value for elt in node.value.elts
                    if isinstance(elt, ast.Constant) and isinstance(elt.value, str)
                ]
    return []


_STUB_METHOD_NAMES = {"parse", "emit", "run"}


def find_stub_methods(path: Path) -> list[str]:
    """Finds 'parse'/'emit'/'run' methods whose entire body is still a
    single 'raise NotImplementedError(...)' — exactly what the
    scaffold generated by 'pld plugin new-local' leaves behind (see
    plugin_scaffold.py) before it's filled in. Static analysis (AST),
    like read_requires_static: works even if the module isn't
    (yet) importable."""
    try:
        tree = ast.parse(path.read_text())
    except (SyntaxError, OSError):
        return []

    found = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef) or node.name not in _STUB_METHOD_NAMES:
            continue
        body = node.body
        if (
            body
            and isinstance(body[0], ast.Expr)
            and isinstance(body[0].value, ast.Constant)
            and isinstance(body[0].value.value, str)
        ):
            body = body[1:]  # skip the docstring, if present
        if len(body) != 1 or not isinstance(body[0], ast.Raise):
            continue
        exc = body[0].exc
        if isinstance(exc, ast.Call) and isinstance(exc.func, ast.Name):
            exc_name = exc.func.id
        elif isinstance(exc, ast.Name):
            exc_name = exc.id
        else:
            exc_name = None
        if exc_name == "NotImplementedError":
            found.append(node.name)
    return found


def missing_requirements(requires: list[str]) -> list[str]:
    """Best-effort check: extracts the package name from each
    requirement string (ignoring the version specifier) and checks
    that it's importable. Not a real dependency resolution (doesn't
    check versions) — just 'is it installed, yes or no'."""
    missing = []
    for req in requires:
        match = _REQ_NAME_RE.match(req.strip())
        if not match:
            continue
        pkg_name = match.group(0).replace("-", "_")
        if importlib.util.find_spec(pkg_name) is None:
            missing.append(req)
    return missing


def discover_local_plugin_dirs(project_root: Path) -> list[Path]:
    dirs = []
    default_dir = project_root / LOCAL_PLUGINS_DIRNAME
    if default_dir.is_dir():
        dirs.append(default_dir)

    env_value = os.environ.get(ENV_VAR_NAME)
    if env_value:
        for part in env_value.split(os.pathsep):
            p = Path(part).expanduser()
            if p.is_dir():
                dirs.append(p)
            else:
                logger.debug("PAYLOAD_PLUGIN_PATH contains a nonexistent folder: %s", p)

    return dirs


def load_module_from_file(path: Path):
    """Public (not just for load_local_plugins): also used by the web
    editor to load and run a single local plugin file without going
    through an entire PluginRegistry."""
    spec = importlib.util.spec_from_file_location(f"payload_local_plugin_{path.stem}", path)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise ImportError(f"couldn't create a spec for {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def extract_plugin_classes(module) -> list[tuple[str, type]]:
    """Returns [(kind, class), ...] for every READER/WRITER/DOCTOR_CHECK
    (singular or plural) declared in the module — same convention as
    load_local_plugins, factored out so the web editor can inspect a
    file without registering it in a PluginRegistry."""
    found: list[tuple[str, type]] = []
    for singular_attr, plural_attr, kind in _ATTR_MAP:
        single = getattr(module, singular_attr, None)
        if single is not None:
            found.append((kind, single))
        plural = getattr(module, plural_attr, None)
        if plural:
            for cls in plural:
                found.append((kind, cls))
    return found


def list_local_plugin_files(project_root: Path) -> list[Path]:
    """.py files in <project_root>/local_plugins/ (only the project's
    own folder, not the additional PAYLOAD_PLUGIN_PATH locations —
    those can live anywhere on the filesystem and aren't in scope for
    'what the web editor for this project is allowed to modify')."""
    d = project_root / LOCAL_PLUGINS_DIRNAME
    if not d.is_dir():
        return []
    return sorted(p for p in d.glob("*.py") if not p.name.startswith("_"))


def _register_one(plugin_cls, source_file: Path, kind: str, register_fn, registry: "PluginRegistry", strict: bool) -> None:
    plugin_label = f"{plugin_cls.__name__} ({source_file.name})"
    try:
        instance = plugin_cls()
        api_version = getattr(instance, "api_version", "0.0")
        check_api_compatibility(getattr(instance, "name", plugin_cls.__name__), api_version)
        register_fn(instance)
        logger.debug("Local plugin loaded: %s (%s) from %s", getattr(instance, "name", "?"), kind, source_file)
    except Exception as e:
        logger.debug("Failed local plugin %s: %s", plugin_label, e)
        if strict:
            raise PluginLoadError(plugin_label, f"local:{kind}", str(e)) from e
        registry.load_failures.append((plugin_label, f"local:{kind}", str(e)))


def load_local_plugins(project_root: Path, registry: "PluginRegistry", strict: bool = True) -> None:
    for plugin_dir in discover_local_plugin_dirs(project_root):
        for py_file in sorted(plugin_dir.glob("*.py")):
            if py_file.name.startswith("_"):
                continue  # convention: files starting with _ aren't plugins (e.g. shared helpers)

            declared_requires = read_requires_static(py_file)
            if declared_requires:
                missing = missing_requirements(declared_requires)
                if missing:
                    logger.debug("Missing dependencies for %s: %s", py_file, missing)
                    if strict:
                        raise MissingPluginDependenciesError(py_file, missing)
                    registry.load_failures.append(
                        (py_file.name, "local:deps", f"missing dependencies: {', '.join(missing)}")
                    )
                    continue  # don't even attempt loading, it would fail anyway

            try:
                module = load_module_from_file(py_file)
            except Exception as e:
                logger.debug("Failed to load file %s: %s", py_file, e)
                if strict:
                    raise PluginLoadError(py_file.name, "local:file", str(e)) from e
                registry.load_failures.append((py_file.name, "local:file", str(e)))
                continue

            for singular_attr, plural_attr, kind in _ATTR_MAP:
                register_fn = {
                    "reader": registry.register_reader,
                    "writer": registry.register_writer,
                    "doctor_check": registry.register_doctor_check,
                }[kind]

                single = getattr(module, singular_attr, None)
                if single is not None:
                    _register_one(single, py_file, kind, register_fn, registry, strict)

                plural = getattr(module, plural_attr, None)
                if plural:
                    for cls in plural:
                        _register_one(cls, py_file, kind, register_fn, registry, strict)
