"""Project table report — a self-contained HTML document describing
every table (status, golden, reader/writer, cluster, tags, notes,
properties, history, output). Generated by ONE function so the webapp
('/api/report/html', opened/printed from the browser) and the CLI
('pld report') always show the same content. Zero dependencies: plain
HTML/CSS, no JavaScript required to read or print it."""
from __future__ import annotations

import html
import time
from pathlib import Path

from payload.core.clusters import resolve_clusters
from payload.core.config import read_raw_sidecar
from payload.core.discovery import all_table_refs, discover_for_history_lenient, resolve_table_config
from payload.web.paths import resolve
from payload.core.golden import check_golden
from payload.core.history import HistoryStore
from payload.core.pipeline import resolve_table_outputs
from payload.core.registry import load_plugins
from payload.core.table_meta import resolve_table_meta


def collect_report_data(root: Path) -> dict:
    """The rows behind /api/report (and the HTML report): every table
    with its status-ish fields. Same data the dashboard table shows."""
    sources, batch_tables, base_config, problems = discover_for_history_lenient(root)
    history = HistoryStore(root)
    registry = load_plugins(strict=False, project_root=root)
    clusters = resolve_clusters(root, base_config)
    table_metas = resolve_table_meta(root, base_config, clusters)
    rows = []
    for ref in all_table_refs(sources, batch_tables):
        name = ref.name
        table_config = resolve_table_config(root, base_config, ref, clusters, table_metas)
        out_dir = resolve(root, table_config.defaults.output_dir)

        pipeline_explicit = bool(table_config.pipeline_stages)
        resolved_reader = resolved_writer = None
        if not pipeline_explicit and not ref.is_batch:
            _, resolved_reader_name, resolved_writer_names = resolve_table_outputs(
                ref.source_paths[0], registry, table_config, out_dir
            )
            resolved_reader = resolved_reader_name
            resolved_writer = resolved_writer_names[0] if resolved_writer_names else None

        output_files = list(out_dir.glob(f"{name}.*")) if out_dir.exists() else []
        out_size = output_files[0].stat().st_size if output_files else None
        golden_result = check_golden(history, name, ref.source_paths, output_files)

        last = history.last_snapshot(name)
        has_sidecar = False if ref.is_batch else bool(read_raw_sidecar(ref.source_paths[0]))
        meta = table_metas.get(name)
        rows.append({
            "name": name,
            "is_batch": ref.is_batch,
            "cluster": meta.cluster if meta else None,
            "tags": meta.tags if meta else [],
            "notes": meta.notes if meta else "",
            "properties": dict(meta.properties) if meta else {},
            "source_count": len(ref.source_paths),
            "source_size": sum(p.stat().st_size for p in ref.source_paths),
            "output_size": out_size,
            "byte_order": table_config.defaults.byte_order,
            "golden_status": golden_result.status,
            "golden_snapshot_id": golden_result.golden_snapshot_id,
            "last_snapshot": {"id": last.id, "timestamp": last.timestamp} if last else None,
            "tip_snapshot_id": history.tip_snapshot_id(name),
            "source_mtime": time.strftime(
                "%Y-%m-%dT%H:%M:%S", time.localtime(max(p.stat().st_mtime for p in ref.source_paths))
            ),
            "has_sidecar": has_sidecar,
            "pipeline_explicit": pipeline_explicit,
            "reader_override": table_config.defaults.reader,
            "writer_override": table_config.defaults.writer,
            "resolved_reader": resolved_reader,
            "resolved_writer": resolved_writer,
        })
    # keep the RAW discovery problem dict; callers map it to readable
    # lines (describe_problems) for their own format (JSON vs HTML)
    return {"tables": rows, "problems": problems}


def _esc(value) -> str:
    return html.escape(str(value if value is not None else ""))


def render_report_html(root: Path) -> str:
    """A standalone, printable HTML report of the whole project."""
    data = collect_report_data(root)
    from payload.core.discovery import describe_problems

    rows = data["tables"]
    total = len(rows)
    with_output = sum(1 for t in rows if t["output_size"] is not None)
    with_golden = sum(1 for t in rows if t["golden_snapshot_id"] is not None)
    problems = describe_problems(data["problems"])

    def status_label(row) -> str:
        if row["golden_status"] == "mismatch":
            return "golden mismatch"
        if row["golden_status"] == "stale":
            return "stale"
        if row["output_size"] is not None:
            return "built"
        return "not built yet"

    summary_rows = "".join(
        f"""
        <tr>
          <td><a href="#t-{_esc(t['name'])}">{_esc(t['name'])}</a></td>
          <td>{_esc(status_label(t))}</td>
          <td>{_esc(t['resolved_reader'] or t['reader_override'] or '—')}</td>
          <td>{_esc(t['resolved_writer'] or t['writer_override'] or '—')}</td>
          <td class="num">{_esc(t['source_size'])} B</td>
          <td class="num">{_esc(t['output_size']) if t['output_size'] is not None else '—'}</td>
          <td>{_esc(t['cluster']) if t['cluster'] else '—'}</td>
        </tr>"""
        for t in rows
    )

    def detail_block(t) -> str:
        tags = " ".join(f'<span class="tag">{_esc(x)}</span>' for x in t["tags"]) or "—"
        props = "".join(f"<tr><td class='k'>{_esc(k)}</td><td>{_esc(v)}</td></tr>" for k, v in sorted(t["properties"].items())) or '<tr><td colspan="2">—</td></tr>'
        notes = f"<p class='notes'>{_esc(t['notes'])}</p>" if t["notes"] else ""
        last = t["last_snapshot"]
        return f"""
        <section id="t-{_esc(t['name'])}" class="table">
          <h2>{_esc(t['name'])} <span class="badge">{_esc(status_label(t))}</span></h2>
          <dl>
            <dt>Reader</dt><dd>{_esc(t['resolved_reader'] or t['reader_override'] or '—')}</dd>
            <dt>Writer</dt><dd>{_esc(t['resolved_writer'] or t['writer_override'] or '—')}</dd>
            <dt>Cluster</dt><dd>{_esc(t['cluster']) if t['cluster'] else '—'}</dd>
            <dt>Tags</dt><dd>{tags}</dd>
            <dt>Source</dt><dd>{t['source_count']} file(s), {t['source_size']} B · {_esc(t['byte_order'])}</dd>
            <dt>Output</dt><dd>{_esc(t['output_size']) if t['output_size'] is not None else '—'} B</dd>
            <dt>Golden</dt><dd>{'#%s' % t['golden_snapshot_id'] if t['golden_snapshot_id'] else '—'}</dd>
            <dt>Last snapshot</dt><dd>{'#%s · %s' % (last['id'], _esc(last['timestamp'])) if last else '—'}</dd>
            <dt>Modified</dt><dd>{_esc(t['source_mtime'])}</dd>
          </dl>
          {notes}
          <h3>Properties</h3>
          <table class="props"><tbody>{props}</tbody></table>
        </section>"""

    detail = "".join(detail_block(t) for t in rows)
    if not rows:
        detail = '<p class="empty">No table in this project.</p>'

    warnings_html = ""
    if problems:
        warnings_html = (
            '<div class="warnings"><strong>Project needs attention</strong><ul>'
            + "".join(f"<li>{_esc(w)}</li>" for w in problems)
            + "</ul></div>"
        )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Table report — {_esc(root.name)}</title>
<style>
  body {{ font-family: -apple-system, "Segoe UI", Roboto, sans-serif; margin: 32px; color: #1c1c1e; }}
  h1 {{ font-size: 22px; margin: 0 0 4px; }}
  .meta {{ color: #666; font-size: 13px; margin-bottom: 18px; }}
  .warnings {{ background: #fff4e5; border: 1px solid #f0c36d; border-radius: 6px; padding: 10px 14px; margin-bottom: 18px; }}
  .warnings ul {{ margin: 6px 0 0; padding-left: 18px; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 13px; }}
  th, td {{ text-align: left; padding: 6px 10px; border-bottom: 1px solid #e2e2e6; }}
  th {{ font-size: 11px; text-transform: uppercase; color: #777; letter-spacing: .04em; }}
  .num {{ text-align: right; font-variant-numeric: tabular-nums; }}
  .badge {{ font-size: 11px; font-weight: 600; color: #fff; background: #6c7a89; border-radius: 999px; padding: 2px 9px; vertical-align: 2px; }}
  .table {{ margin-top: 26px; border-top: 2px solid #333; padding-top: 10px; }}
  .table h2 {{ font-size: 16px; margin: 0 0 8px; }}
  dl {{ display: grid; grid-template-columns: 130px 1fr; gap: 3px 14px; font-size: 13px; margin: 0 0 10px; }}
  dt {{ color: #777; }}
  dd {{ margin: 0; }}
  .tag {{ display: inline-block; background: #eef1f5; border-radius: 999px; padding: 1px 8px; font-size: 12px; margin-right: 4px; }}
  .notes {{ background: #f7f8fa; border-left: 3px solid #c7cdd6; padding: 8px 12px; font-size: 13px; }}
  .props {{ width: auto; min-width: 240px; }}
  .props .k {{ font-weight: 600; }}
  .empty {{ color: #888; }}
  a {{ color: #0057b3; text-decoration: none; }}
  @media print {{ body {{ margin: 12mm; }} .table {{ break-inside: avoid; }} }}
</style>
</head>
<body>
  <h1>Table report — {_esc(root.name)}</h1>
  <p class="meta">Generated {time.strftime("%Y-%m-%d %H:%M:%S")} · {total} table(s), {with_output} with output, {with_golden} with a golden snapshot</p>
  {warnings_html}
  <table>
    <thead><tr><th>Table</th><th>Status</th><th>Reader</th><th>Writer</th><th>Source</th><th>Output</th><th>Cluster</th></tr></thead>
    <tbody>{summary_rows}</tbody>
  </table>
  {detail}
</body>
</html>
"""
