"""
Writer: a C header with TableIR.data's bytes in a 'static const
uint8_t' array. A zero-configuration alternative to obj_writer.py
(which requires objcopy + toolchain.objcopy_target/objcopy_arch): here
you just '#include' the generated file in a single translation unit.

'static const', not 'extern': meant to be included in a SINGLE .c
file — avoids ODR/redefinition errors if the file gets accidentally
included twice. If the array needs to be shared across several .c
files (several translation units), you need a hand-written .h
('extern const uint8_t NAME[];') + .c pair (with the real definition)
— out of scope for this writer, which generates a self-contained
header.

byte_order is irrelevant here: the array is always 'uint8_t[]', one
byte per element — no repack() needed like bin_writer.py needs for a
binary dump of multi-byte values."""
from __future__ import annotations

import re

from pathlib import Path

from payload.core.errors import WriterEmitError
from payload.core.ir import PLUGIN_API_VERSION, TableIR

_INVALID_CHARS_RE = re.compile(r"[^a-zA-Z0-9_]")


def _sanitize_identifier(name: str, fallback_prefix: str) -> str:
    """Sanitizes into a valid C identifier. Besides the obvious case
    (starts with a digit), also prefixes if the result is empty or
    starts with '_' — a name made only of invalid characters (e.g.
    '???') would otherwise sanitize into '___', an identifier reserved
    for the compiler/standard library (§7.1.3)."""
    sanitized = _INVALID_CHARS_RE.sub("_", name)
    if not sanitized or sanitized[0].isdigit() or sanitized[0] == "_":
        sanitized = f"{fallback_prefix}_{sanitized}" if sanitized else fallback_prefix
    return sanitized


class HeaderWriter:
    """Generates a self-contained C header: '#ifndef' guard, '#include
    <stdint.h>', a 'static const uint8_t NAME[N] = {...};' array with
    ir.data's bytes, one per line, with any ir.comments appended at
    end of line. Array name and include guard derived from ir.name
    (sanitized), overridable via [plugin.header] or --opt (--opt
    wins)."""

    name = "header"
    extension = ".h"
    api_version = PLUGIN_API_VERSION
    compatible_readers = None

    def emit(self, ir: TableIR, out_path: Path, config: dict) -> Path:
        if not ir.data:
            raise WriterEmitError(self.name, "TableIR.data is empty: a 'uint8_t[0]' array isn't portable C")

        cli_opts = config.get("cli_opts", {})
        plugin_cfg = config.get("plugin", {}).get(self.name, {})

        array_name = (
            cli_opts.get("array_name")
            or plugin_cfg.get("array_name")
            or _sanitize_identifier(ir.name, "table")
        )
        include_guard = (
            cli_opts.get("include_guard")
            or plugin_cfg.get("include_guard")
            or f"{_sanitize_identifier(ir.name, 'TABLE').upper()}_H"
        )

        comment_by_offset = dict(ir.comments)
        lines = []
        for offset, byte in enumerate(ir.data):
            line = f"    0x{byte:02X},"
            comment = comment_by_offset.get(offset)
            if comment:
                line += f"  // {comment}"
            lines.append(line)
        array_body = "\n".join(lines)

        content = (
            f"#ifndef {include_guard}\n"
            f"#define {include_guard}\n"
            "\n"
            "#include <stdint.h>\n"
            "\n"
            f"/* Generated by payload — {len(ir.data)} bytes, source: {ir.source_path.name} */\n"
            "/* byte_order irrelevant here: array of uint8_t, one byte per element */\n"
            f"static const uint8_t {array_name}[{len(ir.data)}] = {{\n"
            f"{array_body}\n"
            "};\n"
            "\n"
            f"#endif /* {include_guard} */\n"
        )
        out_path.write_text(content)
        return out_path
